- packages/mock-app/src/constants/app-config.json
- packages/services/src/__tests__/aggregationEvent.test.ts
- packages/services/src/__tests__/mocks/constants.ts
- packages/services/src/epcisEvents/aggregationEvent.ts
- packages/services/src/epcisEvents/index.ts
- packages/services/src/epcisEvents/types.ts
- packages/services/src/epcisEvents/validateContext.ts
- packages/services/src/types/epcis.ts
> feat: add aggregation event feature

- .gitignore
- README.md
- packages/mock-app/README.md
- packages/mock-app/src/constants/app-config.example.json
- packages/untp-test-suite/README.md
> feat: clean up config file mock app

- packages/mock-app/src/pages/Scanning.tsx
- packages/services/package.json
- packages/services/src/__tests__/gs1.test.ts
- packages/services/src/identityProviders/GS1Provider.ts
- packages/services/src/identityProviders/IdentityProvider.ts
- packages/services/src/types/imported-modules.d.ts
> chore: update the scanning app to use multiple AIs

- Dockerfile
This is to upgrade node version in Dockerfile from 18 to 21
There's no related tickets or documents
> chore: updated node version in dockerfile

- packages/mock-app/src/pages/Scanning.tsx
> fix: cannot read appConfig's identifyProvider

- packages/storage-server/Dockerfile
- packages/storage-server/README.md
This PR is to add Dockefile for local storage server in mock-app/packages
it's a quick fix, doesn't have ticket
> feat: added dockerfile for local storage server in mock app

- packages/mock-app/README.md
- packages/mock-app/src/__tests__/Header.test.tsx
- packages/mock-app/src/__tests__/helpers.test.tsx
- packages/mock-app/src/components/Header/Header.tsx
- packages/mock-app/src/constants/app-config.example.json
- packages/mock-app/src/pages/Home.tsx
- packages/mock-app/src/pages/Scanning.tsx
- packages/mock-app/src/pages/Verify.tsx
- packages/mock-app/src/types/common.types.ts
- packages/mock-app/src/utils/helpers.ts
- packages/untp-test-suite/README.md
https://github.com/gs-gs/pyx-acrs/issues/65
> refactor: change UI and add api key default verification link

- packages/components/package.json
- packages/components/src/__tests__/helpers.test.tsx
- packages/components/src/components/Button/Button.tsx
- packages/components/src/components/DownloadButton/DownloadButton.tsx
- packages/components/src/components/ImportButton/ImportButton.tsx
- packages/components/src/types/common.types.ts
- packages/components/src/utils/helpers.ts
- packages/mock-app/src/components/Header/Header.tsx
- packages/mock-app/src/hooks/ThemContext.tsx
- packages/mock-app/src/pages/Application.tsx
- packages/mock-app/src/pages/Home.tsx
- packages/mock-app/src/pages/Layout.tsx
- packages/mock-app/src/pages/Scanning.tsx
- packages/mock-app/src/utils/theme/Theme.tsx
- packages/mock-app/src/utils/theme/index.ts
- packages/services/src/__tests__/import.service.test.ts
- packages/services/src/dpp.service.ts
- packages/services/src/epcis.service.ts
- packages/services/src/import.service.ts
- yarn.lock
Style: https://github.com/gs-gs/pyx-acrs/issues/84
https://github.com/uncefact/tests-untp/assets/59736798/3aca1b6c-b981-44f6-80fb-62223eb032db
Recordings
> refactor: create theme mui

- packages/components/src/__tests__/helpers.test.tsx
- packages/components/src/components/Button/Button.tsx
- packages/components/src/components/DownloadButton/DownloadButton.tsx
- packages/components/src/components/ImportButton/ImportButton.tsx
- packages/components/src/types/common.types.ts
- packages/components/src/utils/helpers.ts
- packages/mock-app/src/components/Header/Header.tsx
- packages/mock-app/src/hooks/GlobalContext.tsx
- packages/mock-app/src/hooks/ThemContext.tsx
- packages/mock-app/src/pages/Application.tsx
- packages/mock-app/src/pages/Home.tsx
- packages/mock-app/src/pages/Layout.tsx
- packages/mock-app/src/pages/Scanning.tsx
- packages/mock-app/src/utils/theme/Theme.tsx
- packages/mock-app/src/utils/theme/index.ts
> style: add create theme MUI and hook theme in mock app

- packages/components/src/components/CheckBoxList/CheckBoxList.tsx
> fix: check value field in checkbox before add

- packages/components/package.json
- packages/components/src/components/BarcodeGenerator/BarcodeGenerator.tsx
- packages/components/src/components/BarcodeGenerator/index.ts
- packages/components/src/components/DynamicComponentRenderer/DynamicComponentRenderer.tsx
- packages/components/src/components/index.ts
- packages/mock-app/src/components/GenericFeature/GenericFeature.tsx
- packages/mock-app/src/constants/app-config.dev.example.json
- packages/services/src/epcisEvents/helpers.ts
- packages/services/src/epcisEvents/transformationEvent.ts
- packages/services/src/utils/helpers.ts
- yarn.lock
> feat: implement barcode generator component

- app-config.json
- packages/mock-app/src/constants/app-config.dev.example.json
- packages/mock-app/src/pages/Scanning.tsx
This PR fixes the style of the scanning page to follow the system style from app-config
https://github.com/gs-gs/pyx-acrs/issues/94
> fix: style of scanning page

- .gitignore
- packages/vc-test-suite/.mocharc.json
- packages/vc-test-suite/README.md
- packages/vc-test-suite/helpers.ts
- packages/vc-test-suite/httpService.ts
- packages/vc-test-suite/package.json
- packages/vc-test-suite/respecConfig.json
- packages/vc-test-suite/tests/test-example.test.ts
- packages/vc-test-suite/tsconfig.json
- yarn.lock
This PR adds vc test suite package
https://github.com/gs-gs/fa-ag-trace/issues/523
> feat: setup vc test suite package

- .github/workflows/release-tagging.yml
This PR is to create a git workflow for auto-tagging the main branch and generating a release note after released
Job's logs:
Generated tag:
Generated release note:
> feat: workflow for release tagging and release note

- packages/vc-test-suite/README.md
- packages/vc-test-suite/config.ts
- packages/vc-test-suite/tests/QrlinkEncrypted/helper.ts
- packages/vc-test-suite/tests/QrlinkEncrypted/input/qr-link.json
- packages/vc-test-suite/tests/QrlinkEncrypted/qrlink-encrypted.test.ts
- packages/vc-test-suite/tests/RenderTemplate2024/render-template-2024.test.ts
- packages/vc-test-suite/tests/test-example.test.ts
- packages/vc-test-suite/tsconfig.json
> feat: Create test cases for QR Link / Encryption Test Suite

- packages/mock-app/src/components/Scanner/Scanner.tsx
- packages/mock-app/src/pages/Scanning.tsx
- packages/mock-app/src/types/scanner.types.ts
https://github.com/gs-gs/fa-ag-trace/issues/533
> Fix: unable to scan the long barcodes on mobile devices

- .eslintrc.json
- documentation/docs/introduction/index.md
- documentation/docs/test-suites/index.md
- documentation/docs/test-suites/semantic-interoperability/cli/configuration.md
- documentation/docs/test-suites/semantic-interoperability/cli/extensions.md
- documentation/docs/test-suites/semantic-interoperability/cli/index.md
- documentation/docs/test-suites/semantic-interoperability/cli/installation.md
- documentation/docs/test-suites/semantic-interoperability/cli/usage.md
- documentation/docs/test-suites/semantic-interoperability/getting-started.md
- documentation/docs/test-suites/semantic-interoperability/index.md
This PR:
- Adds documentation for the Tier 2 test suite
- Disables linting for the documentation site
N/A
[Deployed site](https://ashleythedeveloper.github.io/tests-untp/)
> docs: semantic interoperability testing

- .eslintrc.json
- documentation/docs/test-suites/index.md
- documentation/docs/test-suites/technical-interoperability/getting-started.md
- documentation/docs/test-suites/technical-interoperability/identity-resolution/index.md
- documentation/docs/test-suites/technical-interoperability/identity-resolution/testing.md
- documentation/docs/test-suites/technical-interoperability/index.md
- documentation/docs/test-suites/technical-interoperability/installation.md
- documentation/docs/test-suites/technical-interoperability/storage/index.md
- documentation/docs/test-suites/technical-interoperability/storage/testing.md
- documentation/docs/test-suites/technical-interoperability/transparency-graphs/index.md
- documentation/docs/test-suites/technical-interoperability/transparency-graphs/testing.md
- documentation/docs/test-suites/technical-interoperability/untp-extensions/index.md
- documentation/docs/test-suites/technical-interoperability/untp-extensions/qr-link-encryption.md
- documentation/docs/test-suites/technical-interoperability/untp-extensions/rendering.md
- documentation/docs/test-suites/technical-interoperability/verifiable-credentials/index.md
- documentation/docs/test-suites/technical-interoperability/verifiable-credentials/testing.md
This PR:
- Adds documentation for the Tier 1 test suite
N/A
[Deployed site](https://ashleythedeveloper.github.io/tests-untp/)
> docs: technical interoperability testing

- .github/workflows/buld_publish_docs.yml
This PR adds a new workflow to enable automatic deployment of our documentation site - https://uncefact.github.io/tests-untp/
> chore: enable docs deployment workflow

- docker-compose.yml
This PR adds storage service docker integration.
> feat: storage docker integration

- documentation/docs/test-suites/technical-interoperability/getting-started.md
- documentation/docs/test-suites/technical-interoperability/storage/testing.md
This PR adds documentation for storage service testing in the technical interoperability section. It includes instructions for configuring and running the storage tests, as well as viewing the results.
> docs: add storage service test docs

- packages/vc-test-suite/__tests__/storage.helper.test.ts
- packages/vc-test-suite/tests/Storage/helper.ts
- packages/vc-test-suite/tests/Storage/storage.test.ts
This PR updates the storage service tests to improve the decryption process and error handling. It modifies the `decryptData` function to handle JSON parsing of decrypted data and return either a parsed object or the original string. The changes also update the related test cases to reflect this new behaviour.
> chore: update storage service tests

- documentation/docs/test-suites/semantic-interoperability/cli/configuration.md
- documentation/docs/test-suites/semantic-interoperability/cli/usage.md
- packages/untp-test-suite/README.md
- packages/untp-test-suite/__tests__/core/processTestSuite.test.ts
- packages/untp-test-suite/__tests__/core/services/dynamic-loading-schemas/loadingSchema.service.test.ts
- packages/untp-test-suite/__tests__/core/utils/common.test.ts
- packages/untp-test-suite/__tests__/interfaces/cli/testResultProcessor.test.ts
- packages/untp-test-suite/__tests__/interfaces/lib/testSuiteHandler.test.ts
- packages/untp-test-suite/__tests__/interfaces/utils/common.test.ts
- packages/untp-test-suite/__tests__/interfaces/utils/credentials.test.ts
- packages/untp-test-suite/credentials-v0.3.10.json
- packages/untp-test-suite/credentials/DigitalProductPassport_instance-0.3.10.json
- packages/untp-test-suite/integration/cli/untpTest.integration.test.ts
- packages/untp-test-suite/integration/lib/lib.integration.test.ts
- packages/untp-test-suite/integration/mock/untpTestFail/credentialsRemoteSchema.json
- packages/untp-test-suite/integration/mock/untpTestFailuresAndWarnings/credentialsRemoteSchema.json
- packages/untp-test-suite/integration/mock/untpTestPass/credentialsRemoteSchema.json
- packages/untp-test-suite/integration/mock/untpTestPass/data/digitalTraceabilityEvent.json
- packages/untp-test-suite/integration/mock/untpTestWarn/credentialsRemoteSchema.json
- packages/untp-test-suite/integration/mock/untpTestWarn/data/associationEvent.json
- packages/untp-test-suite/src/core/processTestSuite.ts
- packages/untp-test-suite/src/core/services/dynamic-loading-schemas/loadingSchema.service.ts
- packages/untp-test-suite/src/core/services/dynamic-loading-schemas/types.ts
- packages/untp-test-suite/src/core/types/index.ts
- packages/untp-test-suite/src/core/utils/common.ts
- packages/untp-test-suite/src/interfaces/cli/testResultProcessor.ts
- packages/untp-test-suite/src/interfaces/utils/common.ts
- packages/untp-test-suite/src/interfaces/utils/credentials.ts
- packages/untp-test-suite/src/templates/templateMessages/credentialResult.hbs
**When running ` yarn run untp test`**
**Integration test:**
> feat: remote schema support for tier two test suite

- README.md
- app-config.seeding.json
- docker-compose.yml
- seeding-idr-data.sh
- seeding-mock-gs1-data.sh
Develop scripts to seed the IDR service and Mock Verify by GS1 services. The scripts should handle seeding both services with identifiers as specified in the example mock app config file. The integration will include adding a link resolver to the Mock GS1 service and ensuring it points to the IDR service provisioned by the docker-compose file (http://localhost:3001/api/resolver). Seeding is performed using API requests.
The seeding data scripts include an API health check and a retry mechanism. If the API fails after three retry attempts, the script will exit with code 1.
https://github.com/gs-gs/fa-ag-trace/issues/589
> feat: scripts seed data for idr and mock-gs1 services

- digitallink_toolkit_server/Dockerfile
- digitallink_toolkit_server/package.json
- digitallink_toolkit_server/src/GS1DigitalLinkToolkit.js
- digitallink_toolkit_server/src/index.js
- package.json
- packages/services/package.json
- packages/services/src/identityProviders/GS1Provider.ts
- packages/services/src/linkResolver.service.ts
- packages/services/src/types/imported-modules.d.ts
- yarn.lock
This PR replaces the GS1 lib to the temporary cloned one
> chore: add and replace the gs1 library with the temporary cloned one

- app-config.json
- docker-compose.yml
- documentation/docs/mock-apps/services/process-object-event.md
- packages/services/src/__tests__/epcisEvents/objectEvent.test.ts
- packages/services/src/__tests__/features/localStorage.service.test.ts
- packages/services/src/__tests__/helpers.test.ts
- packages/services/src/__tests__/linkResolver.test.ts
- packages/services/src/__tests__/mocks/constants.ts
- packages/services/src/__tests__/validateContext.test.ts
- packages/services/src/epcisEvents/index.ts
- packages/services/src/epcisEvents/objectEvent.ts
- packages/services/src/epcisEvents/transformationEvent.ts
- packages/services/src/epcisEvents/types.ts
- packages/services/src/epcisEvents/validateContext.ts
- packages/services/src/features/index.ts
- packages/services/src/features/localStorage.service.ts
- packages/services/src/linkResolver.service.ts
- packages/services/src/processDPP.service.ts
- packages/services/src/utils/helpers.ts
- packages/services/src/vckit.service.ts
- yarn.lock
This PR adds the processObjectEvent service to mock app
https://github.com/gs-gs/fa-ag-trace/issues/599
> feat: implement process object event service for mock app

- docker-compose.yml
> chore: update vckit latest image in docker compose

- documentation/docs/mock-apps/components/import-button.md
- documentation/docs/mock-apps/components/index.md
- documentation/docs/mock-apps/components/qr-code-scanner-dialog-button.md
- documentation/docs/mock-apps/components/render-check-list.md
This PR adds the documentation for the imported credential components
https://github.com/gs-gs/fa-ag-trace/issues/605
> docs: import credential components

- docker-compose.yml
This PR updates the Docker image used for the identity-resolver-service and mock-global-gs1-resolver services.
> chore: update idr docker image

- docker-compose.yml
This PR aims to update the `vckit-api` Docker image in the `docker-compose.yml`file to the latest version.
https://github.com/gs-gs/fa-ag-trace/issues/688
Docker image:
Running the latest vckit Docker image in the mock-app:
Sending a request to test the RenderTemplate2024 render method:
> chore: update vckit-api docker image

- packages/mock-app/src/components/CredentialRender/CredentialRender.tsx
> fix: update verify apply render template css

- packages/vc-test-suite/config.ts
- packages/vc-test-suite/package.json
- packages/vc-test-suite/tests/QrlinkEncrypted/qrlink-encrypted.test.ts
- yarn.lock
> chore: update vc tests

- documentation/docs/mock-apps/verify-app.md
- packages/mock-app/src/__tests__/Verify.test.tsx
- packages/mock-app/src/pages/Verify.tsx
Modify the Verify page logic to validate the hash against the fetched credential, regardless of the presence of the decryption key in the payload. If the hash does not exist in URL, skip the check
> feat: hash validation on Verify page when key is missing

- docker-compose.yml
> chore: update docker compose with new vckit image

- docker-compose.yml
This PR aims to update the storage-service to the latest version, in the docker-compose.yml. Which includes AWS S3 adapter.
https://github.com/gs-gs/fa-ag-trace/issues/761
- STORAGE_TYPE=local
/v1/documents:
/v1/credentials:
---
- STORAGE_TYPE=aws
/v1/documents:
/v1/credentials:
> chore: update storage-service image to latest version

- app-config.json
- packages/components/src/constants/app-config.json
- packages/mock-app/src/constants/app-config.json
- seeding/idr-data.sh
- seeding/idr-identifier.ato.json
- seeding/idr-identifier.nlis.json
This PR updates the IDR seeding script to add couple namespaces
https://github.com/gs-gs/fa-ag-trace/issues/768
> chore: update idr seeding script

- packages/mock-app/src/templates/v0.5.0/dfr.hbs
This PR aims to fix the coordinate order when constructing Google Maps URLs from GeoJSON data in DFR credentials,
So that location links correctly display on Google Maps.
https://github.com/gs-gs/fa-ag-trace/issues/769
Data will be used to construct the Google Maps URL:
```json 
"geoLocation": {
"type": "Point",
"coordinates": [
-23.5275,
148.1536
]
}
```
If you want to view the full sample DFR credential: [dfr.json](https://github.com/user-attachments/files/17946372/dfr.json)
The constructed Google Maps URL: https://www.google.com/maps?q=-23.5275,148.1536&ll=-23.5275,148.1536&z=13
The Google Map is displayed using the constructed link:
> fix: coordinate order in DFR Google Maps URL construction

- README.md
- documentation/docs/version-mapping/index.md
- documentation/package.json
- documentation/version-mapping/script.js
- documentation/version-mapping/template.hbs
- documentation/yarn.lock
- package.json
- version.json
This PR adds the version mapping page that will be generated by the script only `yarn generate-version-mapping`.
The version mapping documentation is a page on the documentation site, so it needs to generated before releasing a new version of the documentation. Therefore, the versions in the `version.json` file are the upcoming versions for the upcoming release.
The process of generating the version mapping documentation are as follows:
- Read the versions from `version.json` file
- Fetch the dependent versions from the `version.json` file
- Map the versions data to the template
- Append the generated markdown to the `_version-mapping.mdx` file
https://github.com/gs-gs/fa-ag-trace/issues/824
https://github.com/gs-gs/fa-ag-trace/issues/825
> feat: implement version mapping page

- app-config.json
- documentation/docs/mock-apps/services/find-first-matching-key-value.md
- documentation/docs/mock-apps/services/index.md
- packages/components/src/constants/app-config.json
- packages/mock-app/src/constants/app-config.json
- packages/services/src/__tests__/features/findFirstMatchingKeyValue.service.test.ts
- packages/services/src/features/findFirstMatchingKeyValue.service.ts
- packages/services/src/features/index.ts
This PR aims to implement the `findFirstMatchingKeyValue` utility function, along with its documentation and example usage. The function recursively searches for a specific key within nested objects, enabling UNTP components to efficiently locate and extract values from deeply nested structures.
https://github.com/gs-gs/fa-ag-trace/issues/917
- Configure the findFirstMatchingKeyValue utility function:
```json
{
"name": "findFirstMatchingKeyValue",
"parameters": [
{
"targetKey": "credentialSubject"
}
]
}
```
- Configure the BarcodeGenerator component:
```json
{
"name": "BarcodeGenerator",
"type": "Result",
"props": {
"dataPath": {
"primary": {
"ai": "01",
"path": "/registeredId"
}
}
}
}
```
- Issue a new DPP using the BarcodeGenerator component and the getValueFromLocalStorage service …
> feat: implement findFirstMatchingKeyValue utility function

- .gitignore
This PR adds additional git configuration to:
- Preserve required directory "cypress/fixtures/credentials-e2e"
- Ignore test artifacts that shouldn't be under version control
> chore: update git configuration files

- packages/untp-playground/README.md
- packages/untp-playground/infra/README.md
This PR updates the UNTP Playground Infrastructure documentation to be more comprehensive. It documents the tools, services, and processes used to deploy the playground to the respective environments.
> docs: update playground infra documentation

- packages/untp-playground/__tests__/lib/credentialService.test.ts
- packages/untp-playground/src/lib/credentialService.ts
Not sure if it's a bug-fix or feature, but supports pre-release versions when parsing the context URL, so that the correct schema file can be pulled.
> Fix version detection for prerelease

- packages/untp-playground/src/lib/schemaValidation.ts
This PR extends the extension configuration to include the AATP DLP 0.4.1-beta1 release.
> feat: add dlp 0.4.1-beta1 release

- .github/workflows/ci_cd-untp-playground.yml
- packages/untp-playground/__tests__/contexts/TestReportContext.test.tsx
- packages/untp-playground/__tests__/lib/reportService.test.ts
- packages/untp-playground/config.ts
- packages/untp-playground/infra/README.md
- packages/untp-playground/infra/infra/app.ts
- packages/untp-playground/src/lib/reportService.ts
- packages/untp-playground/src/lib/schemaValidation.ts
- packages/untp-playground/src/types/report.ts
https://github.com/uncefact/tests-untp/issues/251
> feat: add report name to playground report

- e2e/cypress/e2e/untp-playground/jsonld-expansion-validation.cy.ts
- e2e/cypress/e2e/untp-playground/upload-invalid-credential.cy.ts
- e2e/cypress/support/commands/untp-playground.ts
- packages/untp-playground/__tests__/app/page.test.tsx
- packages/untp-playground/__tests__/components/CredentialUploader.test.tsx
- packages/untp-playground/__tests__/components/ErrorDialog.test.tsx
- packages/untp-playground/__tests__/lib/utils.test.ts
- packages/untp-playground/constants.ts
- packages/untp-playground/src/app/layout.tsx
- packages/untp-playground/src/app/page.tsx
- packages/untp-playground/src/components/ClientLayout.tsx
- packages/untp-playground/src/components/CredentialUploader.tsx
- packages/untp-playground/src/components/ErrorDialog.tsx
- packages/untp-playground/src/components/TestResults.tsx
- packages/untp-playground/src/components/ValidationDetailsSheet.tsx
- packages/untp-playground/src/contexts/ErrorContext.tsx
- packages/untp-playground/src/lib/credentialService.ts
- packages/untp-playground/src/lib/utils.ts
https://github.com/uncefact/tests-untp/issues/224
> feat: improve UNTP playground error messages

- packages/untp-playground/__tests__/components/DownloadReport.test.tsx
- packages/untp-playground/src/components/DownloadReport.tsx
https://github.com/uncefact/tests-untp/issues/261
> fix: download report label unexpectedly changing

- packages/mock-app/src/templates/v0.6.0/digital_facility_record/example-data.json
- packages/mock-app/src/templates/v0.6.0/digital_facility_record/template.hbs
This PR introduces a render template for the v0.6.0 Digital Facility Record data model. To illustrate the features of this render template, I've attached a single image demonstrating the basic rendering of a Digital Facility Record. To explore additional features, such as parameterised colours, fonts, font weights, responsive design and dynamic rendering of elements based on the presence of non-required values, you can use the live preview functionality in [Render Template Studio](https://render-template-studio.pyx.io/).
> feat: add 0.6.0 dfr render template

- packages/untp-test-suite/src/schemas/digitalFacilityRecord/v0.6.0/schema.json
This PR add the schema for the 0.6.0 DFR data model to the untp-test-suite.
> feat: add 0.6.0 schema

- e2e/constant.ts
- e2e/cypress/e2e/issue_workflow_test/DFR/issueDFR.cy.ts
- e2e/cypress/fixtures/app-config.json
This PR updates the existing e2e tests for the Digitality Facility Record, specifically updating the app config and updating the identifiers used. 
**NOTE**: 
- This PR has a dependency on PR #270 being merged.
- While making the updates, I've identified a false positive within the ["Render DFR end-to-end testing flow"](https://github.com/uncefact/tests-untp/blob/next/e2e/cypress/e2e/vc_render/render_dfr.cy.ts) test cases, specifically the ["should render template when content is exist"](https://github.com/uncefact/tests-untp/blob/bf7b7c627007227bce3538e0e3b807599674bac1/e2e/cypress/e2e/vc_render/render_dfr.cy.ts#L43) test case where it's passing even though the credential isn't rendering due to the issue PR [#279](https://github.com/uncefact/project-vckit/pull/279) addresses. A …
> test: update dfr to v0.6.0

- packages/untp-test-suite/src/schemas/digitalIdentityAnchor/v0.6.0/schema.json
This PR add the schema for the 0.6.0 DIA data model to the untp-test-suite.
> feat: add 0.6.0 dia schema

- packages/untp-test-suite/src/schemas/digitalProductPassport/v0.6.0/schema.json
This PR adds the schema for the 0.6.0 DPP data model to the untp-test-suite.
> feat: add v0.6.0 dpp schema

- documentation/docs/migration-guides/v0.6.0.md
The pull request revises the migration guide to incorporate instructions for Digital Conformity Credential v0.6.0. I have elaborated on the changes made, which I believe is justified. Additionally, I have reordered the DRF section for improved clarity.
> docs: add 0.6.0 dcc migration guide

- packages/untp-test-suite/src/schemas/digitalTraceabilityEvent/v0.6.0/schema.json
This PR adds the schema for the 0.6.0 DTE data model to the untp-test-suite.
> feat: add v0.6.0 dte schema

- packages/mock-app/src/templates/v0.6.0/digital_traceability_event/example-data.json
- packages/mock-app/src/templates/v0.6.0/digital_traceability_event/template.hbs
This PR introduces a render template for the v0.6.0 Digital Traceability Events data model. To illustrate the features of this render template, I've attached images demonstrating the basic rendering of a Digital Traceability Event. To explore additional features, such as parameterised colours, fonts, font weights, responsive design and dynamic rendering of elements based on the presence of non-required values, you can use the live preview functionality in the [Render Template Studio](https://render-template-studio.pyx.io/).
> feat: add v0.6.0 dte render template

- documentation/docs/migration-guides/v0.6.0.md
The pull request revises the migration guide to incorporate instructions for Digital Product Passport v0.6.0. I have elaborated on the changes made, which I believe are justified.
> docs: add v0.6.0 dpp migration guide

- documentation/docs/migration-guides/v0.6.0.md
This PR removes the relative FacilityVerification and ProductVerification types from the migration guide as they aren't needed.
> docs: remove relative FacilityVerification and ProductVerification types

- packages/untp-test-suite-mocha/package.json
- yarn.lock
fixes #328
Downgrade dependencies that require ES Modules and does not support commonjs anymore
fixes #328
> downgrade chai and node-fetch
