uncefact/tests-untp

- .github/workflows/build_test.yml
Chore: https://github.com/gs-gs/fa-ag-trace/issues/524
> chore: setup cicd testing

- .github/workflows/package.yml
> feat(cd): ghcr.io setup and docker image build workflow

- .eslintrc.json
- packages/vc-test-suite/README.md
- packages/vc-test-suite/__tests__/helpers.test.ts
- packages/vc-test-suite/__tests__/storage.helper.test.ts
- packages/vc-test-suite/config.ts
- packages/vc-test-suite/helpers.ts
- packages/vc-test-suite/httpService.ts
- packages/vc-test-suite/jest.config.js
- packages/vc-test-suite/package.json
- packages/vc-test-suite/tests/QrlinkEncrypted/qrlink-encrypted.test.ts
- packages/vc-test-suite/tests/RenderTemplate2024/render-template-2024.test.ts
- packages/vc-test-suite/tests/Storage/helper.ts
- packages/vc-test-suite/tests/Storage/storage.test.ts
This PR adds storage service tests to the VC test suite. It includes new test cases for storing and retrieving both encrypted and unencrypted credentials, handling GUID collisions, and verifying public access to stored credentials.
> feat: add storage service tests

- packages/vc-test-suite/__tests__/storage.helper.test.ts
- packages/vc-test-suite/tests/Storage/helper.ts
- packages/vc-test-suite/tests/Storage/storage.test.ts
This PR updates storage tests in the vc-test-suite package. It modifies the decryptData function to handle non-base64 decryption results and updates related test cases.
> chore: update storage tests

- documentation/Dockerfile
This PR addresses an issue with the documentation site setup in the Dockerfile. The changes aim to improve the development workflow when using `docker-compose up`. 
This PR accomplishes:
1. Fixes the documentation start command: Replaces `yarn serve` with `yarn start`.
2. Enables live updates: Allows developers to make changes to the documentation and see them reflected immediately within the container.
3. Resolves content display issue: Previously, mounting the documentation folder to propagate changes was overriding the build folder, resulting in no content being displayed. This PR corrects that problem.
These modifications ensure that:
- Developers can run `docker-compose up` and access a fully functional documentation site.
- Any changes made to the documentation are immediately …
> fix: update documentation start command

- documentation/docs/mock-apps/configuration/index.md
- documentation/docs/mock-apps/dependent-services/verifiable-credential-service.md
This PR updates the VCKit documentation URLs in the mock apps configuration and verifiable credential service pages. It replaces the old GitHub repository link with the new documentation site URL.
> docs: update vc docs url

- packages/mock-app/package.json
- yarn.lock
This PR fixes a compatibility issue by pinning the hashing library to a specific version (v5.5.3). This change ensures consistent output across different services.
> fix: pin hashing library to v5.5.3

- documentation/docs/mock-apps/common/identifier-key-path.md
- documentation/docs/mock-apps/services/process-aggregation-event.md
- documentation/docs/mock-apps/services/process-dpp.md
- documentation/docs/mock-apps/services/process-transaction-event.md
- documentation/docs/mock-apps/services/process-transformation-event.md
- packages/services/package.json
- packages/services/src/__tests__/features/localStorage.service.test.ts
- packages/services/src/__tests__/helpers.test.ts
- packages/services/src/epcisEvents/aggregationEvent.ts
- packages/services/src/epcisEvents/transactionEvent.ts
- packages/services/src/epcisEvents/types.ts
- packages/services/src/features/localStorage.service.ts
- packages/services/src/linkResolver.service.ts
- packages/services/src/processDPP.service.ts
- packages/services/src/utils/helpers.ts
This PR adds the concat service to construct the elementString of the identifier.
The `identifierKeyPath` now can be `string` for the path like `/productIdentifier/0/identifierValue` or `object` to construct the appropriate identifier like 
```
{
...
"identifierKeyPath": {
"function": "concatService",
"args": [
{ "type": "text", "value": "(01)" },
{ "type": "path", "value": "/productIdentifier/0/identifierValue" },
{ "type": "text", "value": "(10)" },
{ "type": "path", "value": "/batchIdentifier/0/identifierValue" },
{ "type": "text", "value": "(21)" },
{ "type": "path", "value": "/itemIdentifier/0/identifierValue" }
]
}
...
}
```
https://github.com/gs-gs/fa-ag-trace/issues/564
> feat: enhance construct elementString

- app-config.json
- documentation/docs/mock-apps/services/process-aggregation-event.md
- documentation/docs/mock-apps/services/process-association-event.md
- packages/services/src/__tests__/epcisEvents/associationEvent.test.ts
- packages/services/src/__tests__/mocks/constants.ts
- packages/services/src/epcisEvents/associationEvent.ts
- packages/services/src/epcisEvents/index.ts
- packages/services/src/types/types.ts
- packages/services/src/validateContext.ts
This PR adds the processAssociationEvent function 
https://github.com/gs-gs/fa-ag-trace/issues/656
> feat: implement processAssociationEvent function

- app-config.json
- documentation/docs/mock-apps/services/process-aggregation-event.md
- documentation/docs/mock-apps/services/process-digital-conformity-credential.md
- documentation/docs/mock-apps/services/process-digital-facility-record.md
- documentation/docs/mock-apps/services/process-digital-identity-anchor.md
- documentation/docs/mock-apps/services/process-dpp.md
- documentation/docs/mock-apps/services/process-object-event.md
- documentation/docs/mock-apps/services/process-transaction-event.md
- documentation/docs/mock-apps/services/process-transformation-event.md
- packages/services/src/__tests__/mocks/constants.ts
- packages/services/src/__tests__/processDigitalConformityCredential.test.ts
- packages/services/src/index.ts
- packages/services/src/processDigitalConformityCredential.service.ts
- packages/services/src/types/types.ts
- packages/services/src/validateContext.ts
This PR adds the processDigitalConformityCredential function
https://github.com/gs-gs/fa-ag-trace/issues/669
> feat: implement processDigitalConformityCredential function

- documentation/docs/test-suites/technical-interoperability/getting-started.md
- documentation/docs/test-suites/technical-interoperability/storage/testing.md
- documentation/docs/test-suites/technical-interoperability/untp-extensions/rendering.md
- packages/services/src/vckit.service.ts
- packages/vc-test-suite/__tests__/httpService.test.ts
- packages/vc-test-suite/config.ts
- packages/vc-test-suite/httpService.ts
- packages/vc-test-suite/tests/QrlinkEncrypted/qrlink-encrypted.test.ts
- packages/vc-test-suite/tests/RenderTemplate2024/render-template-2024.test.ts
This PR adds the ability to pass custom headers to requests across the tier 1 test suite. This update allows users to specify headers such as authorization tokens in the configuration, making the test suites more flexible when interacting with services that require specific HTTP headers.
It also includes relevant documentation updates and test cases to validate this new feature, ensuring headers are plain objects and that they are passed correctly in requests.
**NOTE:** It has been uncovered that the render tests are failing. This was hidden due to the authorisation error this PR seeks to resolve. Another PR will be raised to fix the tests.
> chore: pass headers to request

- documentation/docs/mock-apps/common/verifiable-credentials.md
> docs: update document for enveloping proof flow

- documentation/docs/mock-apps/dependent-services/identity-resolution-service.md
Add Documentation for Seeding Script in IDR and Mock GS1 Service to Mock App Guide
N/A
N/A
N/A
> docs: add documentation for seeding Script in IDR and Mock GS1 services

- .github/workflows/build_test.yml
- documentation/docs/mock-apps/components/import-button.md
- documentation/docs/mock-apps/components/qr-code-scanner-dialog-button.md
This PR fixes documentation build issues. Changes include:
1. Added a new GitHub Actions workflow job `build_docs` to ensure the docs can be built
2. Fixed table formatting in markdown files to properly escape special characters
> fix: docs build

- app-config.json
- documentation/docs/mock-apps/services/convert-object-to-array-1-item.md
- documentation/docs/mock-apps/services/process-aggregation-event.md
- documentation/docs/mock-apps/services/process-traceability-event.md
- documentation/docs/mock-apps/services/process-transaction-event.md
- documentation/docs/mock-apps/services/process-transformantion-event-only.md
- packages/mock-app/src/constants/app-config.json
- packages/services/src/__tests__/aggregationEvent.test.ts
- packages/services/src/__tests__/epcisEvents/objectEvent.test.ts
- packages/services/src/__tests__/epcisEvents/traceabilityEvent.test.ts
- packages/services/src/__tests__/epcisEvents/transformationEventOnly.test.ts
- packages/services/src/__tests__/helpers.test.ts
- packages/services/src/__tests__/mocks/constants.ts
- packages/services/src/__tests__/transactionEvent.test.ts
- packages/services/src/__tests__/transformationEvent.test.ts
- packages/services/src/__tests__/validateContext.test.ts
- packages/services/src/epcisEvents/aggregationEvent.ts
- packages/services/src/epcisEvents/associationEvent.ts
- packages/services/src/epcisEvents/index.ts
- packages/services/src/epcisEvents/objectEvent.ts
- packages/services/src/epcisEvents/traceabilityEvent.ts
- packages/services/src/epcisEvents/transactionEvent.ts
- packages/services/src/epcisEvents/transformationEventOnly.ts
- packages/services/src/types/types.ts
- packages/services/src/utils/helpers.ts
- packages/services/src/validateContext.ts
This PR adds processTraceabilityEvent function and the convertObjectToArray1Item function to support the existing event using the data from JSON form to issue an array credentialSubject.
Example flow for Object Event
```mermaid
flowchart TD
A[Client] --JSON form radio button select an event--> B[Traceability Event]
B --An array data--> C[Object Event]
A --JSON form simple Object event--> D[Convert object data to array 1 item data]
D --An array of 1 Object event data--> C
```
https://github.com/gs-gs/fa-ag-trace/issues/627
> feat: support array for traceability event and existing events

- packages/mock-app/src/templates/v0.5.0/dpp.hbs
This PR aims to remove the View more button and its functionality from the DPP render template v0.5.0.
Desktop UI:
Mobile UI:
> chore: remove View more button in the DPP render template 0.5.0

- documentation/docs/test-suites/semantic-interoperability/cli/configuration.md
This PR updates the documentation in the Test Suites section (Tier 2) to provide clearer guidance on working with extensions and configuration for extentions. Key changes include:
- Enhanced the Extensions section with detailed examples for testing industry-specific protocols (AATP)
- Added comprehensive guidance for both local and remote schema testing methods
- Clarified configuration file setup process with practical examples
- Added detailed examples of using both local schema directories and remote schema URLs
These changes aim to make it easier for implementors to understand how to test their credentials against both core UNTP data models and industry-specific extensions.
> docs: update extensions section

- docker-compose.yml
> chore: update idr docker image for link types voc

- documentation/docs/mock-apps/common/http-headers.md
- documentation/docs/mock-apps/common/payload-type.md
- documentation/docs/mock-apps/components/import-button.md
- documentation/docs/mock-apps/components/qr-code-scanner-dialog-button.md
- documentation/docs/mock-apps/components/render-check-list.md
- documentation/docs/mock-apps/configuration/vc-component-config.md
This PR updates the diagram for the import and scanning component.
https://github.com/gs-gs/fa-ag-trace/issues/667
> docs: add diagrams for the import and scanning component

- docker-compose.yml
- packages/untp-playground/src/components/DownloadCredential.tsx
This PR fixes the test credential path prefix in a deployed environment.
**Without Prefix**
**With Prefix**
> fix: test credential path

- packages/untp-playground/infra/infra/app.ts
- packages/untp-playground/infra/package.json
Fixes error when running `pulumi up`
```
error: error reading build output: failed to read downloaded context: failed to load cache key: Get "http://build-context-j5ak49wxfmfbsn5fsifh6z0zg": context not found
```
by migrating to [docker-build](https://www.pulumi.com/blog/docker-build/) provider.
> fix: migrate to docker-build prvider

- docker-compose.yml
- packages/services/src/identityProviders/GS1Provider.ts
- packages/services/src/linkResolver.service.ts
This PR updates the `getDlrPassport` function to extract the DPP link resolver from the `sustainabilityInfo` linkType instead of the `certificationInfo` linkType. This change ensures that the Scanning page can navigate to the correct DPP link resolver and the Verify page can successfully load and render the DPP template.
Additionally, it fixes the Mock GS1 MinIO console address on port 9090, allowing successful access to the Mock GS1 MinIO console.
https://github.com/gs-gs/fa-ag-trace/issues/800
- Issue a new DPP:
--- 
- Scan the barcode and navigate to the Verify page:
https://github.com/user-attachments/assets/26b51f8e-504b-403f-929c-b83bdd69d979
> fix: update the getDlrPassport function to extract link resolver from `sustainabilityInfo` instead of `certificationInfo` link type

- packages/untp-playground/__tests__/app/page.test.tsx
- packages/untp-playground/__tests__/lib/credentialService.test.ts
- packages/untp-playground/__tests__/lib/schemaValidation.test.ts
- packages/untp-playground/src/app/page.tsx
- packages/untp-playground/src/components/TestResults.tsx
- packages/untp-playground/src/lib/credentialService.ts
- packages/untp-playground/src/lib/schemaValidation.ts
This PR implements the capability for UNTP playground can work with the extension and flexible with the version of the schema
https://github.com/gs-gs/fa-ag-trace/issues/786
> feat: support multi version and extension

- packages/untp-playground/__tests__/components/TestResults.test.tsx
- packages/untp-playground/src/components/TestResults.tsx
This PR fixes scenarios where the success feedback (confetti) was shown despite validation errors.
https://github.com/user-attachments/assets/4d750123-3736-467e-94c2-3669e027e542
> fix: prevent confetti from triggering on validation errors

- packages/untp-test-suite/package.json
I just came across this while trying to fix something else:
Without this change, `yarn build` copies the templates to the wrong location after the first build, so any changes are not included:
When nothing exists, it works perfectly, creating the `templateMessages` directory with the files as expected:
```console
(venv) {fix-build-cp-of-templates} ~/dev/gosource/tests-untp/packages/untp-test-suite$ rm build/templates/templateMessages -rf
(venv) {fix-build-cp-of-templates} ~/dev/gosource/tests-untp/packages/untp-test-suite$ yarn build && ls -l build/templates/templateMessages
yarn run v1.22.22
$ tsc --build --clean && tsc && cp -r src/templates/templateMessages/ build/templates/templateMessages
Done in 1.41s.
total 16
-rw-rw-r-- 1 michael michael 134 Jan 29 12:48 credentialResult.hbs …
```
> fix(build): Copy templates to correct directory during yarn build.

- packages/untp-test-suite/__tests__/templates/mapper.test.ts
- packages/untp-test-suite/src/templates/mapper.ts
- packages/untp-test-suite/src/templates/templateMessages/errors.hbs
If the error message includes a regex with, for example, backslashes (as is often the case with regexes), the untp test function fails to report on the results, instead erroring with invalid character when the error report is converted to a JSON object.
While working on a [proposal for more extensible JSON schema from jargon](https://github.com/absoludity/tests-untp/pull/1) I found that I couldn't run `yarn run untp test` with a schema that included certain regexes (specifically, the XMLSCHEMA11-2 regex for datetime), but instead, would get:
```console
yarn run untp test
yarn run v1.22.22
$ node build/interfaces/cli/cli.js test
Run Untp test suites failed
SyntaxError: Bad escaped character in JSON at position 261
Done in 0.66s.
```
It took me way too long (partly my own fault) to realise …
> fix(errors): error messages need to be escaped to ensure valid json.

- packages/untp-playground/src/lib/contextValidation.ts
This PR aims fix the silent failure occurring in the JSON-LD Document Expansion and Context Validation step of the UNTP Playground.
https://github.com/gs-gs/fa-ag-trace/issues/954
Verify that the context validation error should be displayed on the UI instead of failing silently.
> fix: enhance error handling in context validation

- e2e/cypress/e2e/untp-playground/jsonld-expansion-validation.cy.ts
- e2e/cypress/support/commands/untp-playground.ts
- e2e/cypress/support/index.d.ts
- packages/untp-playground/__tests__/lib/contextValidation.test.ts
- packages/untp-playground/src/lib/contextValidation.ts
This PR implements end-to-end tests for the [JSON-LD expansion validation step](https://github.com/gs-gs/fa-ag-trace/issues/908) in the UNTP playground. These tests ensure the feature functions correctly across all scenarios, including valid JSON-LD credential expansion and various invalid JSON-LD cases. Additionally, they verify that error messages are displayed correctly in the UI.
https://github.com/gs-gs/fa-ag-trace/issues/955
Valid case:
Missing "credentialSubject/invalid" property in the context:
Unresolvable/invalid context URL:
Invalid term:
> test: add JSON-LD expansion and validation e2e tests

- .github/workflows/build_test.yml
- docker-compose.e2e.yml
This PR fixes #234 and adds a dependency for app service in e2e docker compose on untp-playground that prevents running `yarn install && yarn cache clean` multiple times because of untp-playground build in progress, that changes the context for app.
https://github.com/actions/runner-images/issues/2840#issuecomment-1284059930
> chore: free up space on the runner before e2e tests

- .github/workflows/build_test.yml
- docker-compose.e2e.yml
- docker-compose.yml
- packages/untp-playground/Dockerfile
This PR resolves a build failure in the UNTP Playground when provisioning the service locally or in the pipeline using Docker/Docker Compose (see issue #265).
The issue arose because the Dockerfile referenced the Yarn lock file in the `untp-playground` package directory, but the repository structure places the Yarn lock file in the root directory, with dependencies listed in the `package.json` file within the packages directory.
I identified three possible solutions:
**Option 1**  
Copy the Yarn lock file into the `untp-playground` package within the workflow file. This simple solution fixes the pipeline issue but leaves local builds broken.
**Option 2**  
Use the Docker Compose [additional_contexts](https://docs.docker.com/reference/compose-file/build/#additional_contexts) attribute to …
> fix: untp playground build

- e2e/cypress/e2e/issue_workflow_test/DIA/issueDIA.cy.ts
- e2e/cypress/fixtures/app-config.json
This PR updates the existing e2e tests for the Digital Identity Anchor, specifically:
- Update the app configuration to:
- Use the latest v0.6.0 DIA data model/render template
- Extract the registered ID from the DIA as opposed to using the value of the credentials id
- Update the name of some test steps from DCC > DIA
- Construct the appropriate IDR link for the verifyLinkType test case, as opposed to validating that the default link type is accessible (false positive test case)
- Update the schema validation configuration to use the v0.6.0 schema
**NOTE**: 
- This PR has a dependency on PR #276 being merged.
- While making the updates, I've identified a false positive within the ["Render DIA end-to-end testing flow"](https://github.com/uncefact/tests-untp/blob/next/e2e/cypress/e2e/vc_ren …
> test: update dia tests to v0.6.0

- packages/untp-test-suite/src/schemas/digitalConformityCredential/v0.6.0/schema.json
This PR add the schema for the 0.6.0 DCC data model to the untp-test-suite.
> feat: add v0.6.0 dcc schema

- packages/mock-app/package.json
- yarn.lock
This PR bumps the VCkit Render Package to the latest version.
This addresses a known bug that occurs when attempting to render a v0.6.0 credential within the reference implementation, due to a change in the context files used in UNTP. See PR [#279](https://github.com/uncefact/project-vckit/pull/279) for more information.
A subsequent PR will be raised to address Issue #272
> chore: bump vckit render package

- e2e/cypress/page/renderPage.ts
- packages/mock-app/src/components/CredentialRender/CredentialRender.tsx
This PR addresses the false positive render test cases as described in ticket #272.
I've attempted to integrate a "robust" test case where we take a snapshot of the screen once the credential is rendered, but after a few runs, I'm unable to get consistent results even with a failure threshold of 5%.
For now, I've instead taken a more straightforward approach by adding two test IDs, one for the loading spinner (loading-indicator) and the other for the element that is only rendered if a template is present (rendered-template).
Fixes #272
> test: fix false positive render test cases

- README.md
- documentation/docs/mock-apps/common/verify-link.md
- documentation/docs/mock-apps/configuration/service-config.md
- documentation/docs/mock-apps/conformity-credential.md
- documentation/docs/mock-apps/services/index.md
- documentation/docs/mock-apps/services/process-dpp.md
- documentation/versioned_docs/version-0.1.0/mock-apps/common/verify-link.md
- documentation/versioned_docs/version-0.1.0/mock-apps/configuration/service-config.md
- documentation/versioned_docs/version-0.1.0/mock-apps/conformity-credential.md
- documentation/versioned_docs/version-0.1.0/mock-apps/services/index.md
- documentation/versioned_docs/version-0.1.0/mock-apps/services/process-dpp.md
- documentation/versioned_docs/version-0.2.0/mock-apps/common/verify-link.md
- documentation/versioned_docs/version-0.2.0/mock-apps/configuration/service-config.md
- documentation/versioned_docs/version-0.2.0/mock-apps/conformity-credential.md
- documentation/versioned_docs/version-0.2.0/mock-apps/services/index.md
- documentation/versioned_docs/version-0.2.0/mock-apps/services/process-dpp.md
- packages/mock-app/documents/configure-document.md
- packages/mock-app/package.json
- packages/mock-app/src/__tests__/Header.test.tsx
- packages/mock-app/src/constants/app-config.dev.example.json
- packages/mock-app/src/constants/app-config.example.json
- packages/services/src/__tests__/helpers.test.ts
This PR resolves the port conflict between the IDR service (provisioned by Docker Compose) and the Reference Implementation by setting the port used by the Reference Implementation to port 3003. This port aligns with the port used by the Reference Implementation within the E2E tests configuration. The documentation has been updated to reflect the change.
Fixes #315
> fix: conflicting app ports

- e2e/cypress.config.ts
This PR increases the timeout for Cypress commands from 4 to 10 seconds to address an issue with a VCDM verification test case timing out within `untp-playground/vcdm-validation.cy.ts` in the pipeline.
> tests: increase timeout

- packages/untp-test-suite-mocha/package.json
- yarn.lock
This PR downgrades the [chalk package](https://www.npmjs.com/package/chalk/v/4.1.2) used within the `untp-test-suite-mocha` package to a compatible version that supports CommonJS (as warned in the [v5 README](https://github.com/chalk/chalk#install)).
> fix: downgrade chalk to compatible version
